sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t syam-s-achari/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true syam-s-achari/docker-react npm run test
